apiVersion: v1
kind: Service
metadata:
  name: mongo-config
  namespace: mongo-shard-cluster 
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    role: mongo-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard1
  namespace: mongo-shard-cluster 
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    role: mongo-shard1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard2
  namespace: mongo-shard-cluster 
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    role: mongo-shard2
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-router
  namespace: mongo-shard-cluster 
spec:
  ports:
  - port: 27017
  selector:
    role: mongo-router
  type: LoadBalancer
